turmastd = {
  'PIINT7T1A': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1B': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1C': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1D': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1E': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1F': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1G': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'PIINT7T1H': {
    'TURNO': 'INTEGRAL 7H',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO EM TEMPO INTEGRAL',
    'ANO/SERIE/OUTROS': '1ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR'
  },
  'EMMAT3A': {
    'TURNO': 'MATUTINO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'EMMAT3B': {
    'TURNO': 'MATUTINO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'EMMAT3C': {
    'TURNO': 'MATUTINO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'NEMMATLCHA': {
    'TURNO':
    'MATUTINO',
    'MODALIDADE':
    'EDUCACAO REGULAR',
    'NÍVEL':
    'ENSINO MÉDIO',
    'OFERTA':
    'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS':
    '2ª SÉRIE - ITINERÁRIO FORMATIVO - LINGUAGENS E SUAS TECNOLOGIAS E CIÊNCIAS HUMANAS E SOCIAIS APLICADAS'
  },
  'NEMMATLCHB': {
    'TURNO':
    'MATUTINO',
    'MODALIDADE':
    'EDUCACAO REGULAR',
    'NÍVEL':
    'ENSINO MÉDIO',
    'OFERTA':
    'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS':
    '2ª SÉRIE - ITINERÁRIO FORMATIVO - LINGUAGENS E SUAS TECNOLOGIAS E CIÊNCIAS HUMANAS E SOCIAIS APLICADAS'
  },
  'NEMMATMCNA': {
    'TURNO':
    'MATUTINO',
    'MODALIDADE':
    'EDUCACAO REGULAR',
    'NÍVEL':
    'ENSINO MÉDIO',
    'OFERTA':
    'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS':
    '2ª SÉRIE - ITINERÁRIO FORMATIVO - MATEMÁTICA E SUAS TECNOLOGIAS E CIÊNCIAS DA NATUREZA E SUAS TECNOLOGIAS'
  },
  'NEMMATTIA': {
    'TURNO': 'MATUTINO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '2ª SÉRIE - ITINERÁRIO FORMATIVO - TRANSDISCIPLINAR I'
  },
  'TFS3NOTF2E6A': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO FORMATIVO II: TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VI'
  },
  'TFS3NOTF2E6B': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO FORMATIVO II: TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VI'
  },
  'TFS3NOTF2E6C': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO FORMATIVO II: TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VI'
  },
  'TFS3NOTTFE7A': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO FORMATIVO II: TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VII'
  },
  'TFS3NOTTFE7B': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO FORMATIVO II: TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VII'
  },
  'EJAJ3NOTJ3E6A': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO JUVENIL - TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VI'
  },
  'EJAJ3NOTJ3E6B': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO JUVENIL - TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VI'
  },
  'EJAJ3NOTJ3E6C': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO JUVENIL - TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VI'
  },
  'EJAJ3NOTJ3E7A': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO DE JOVENS E ADULTOS - EJA',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'EJA - TEMPO JUVENIL - TERCEIRO SEGMENTO',
    'ANO/SERIE/OUTROS': 'ETAPA VII'
  },
  'EMNOT3A': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'EMNOT3B': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'EMNOT3C': {
    'TURNO': 'NOTURNO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'EMVES3A': {
    'TURNO': 'VESPERTINO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'EMVES3B': {
    'TURNO': 'VESPERTINO',
    'MODALIDADE': 'EDUCACAO REGULAR',
    'NÍVEL': 'ENSINO MÉDIO',
    'OFERTA': 'ENSINO MÉDIO',
    'ANO/SERIE/OUTROS': '3ª Série'
  },
  'NEMVESLCHA': {
    'TURNO':
    'VESPERTINO',
    'MODALIDADE':
    'EDUCACAO REGULAR',
    'NÍVEL':
    'ENSINO MÉDIO',
    'OFERTA':
    'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS':
    '2ª SÉRIE - ITINERÁRIO FORMATIVO - LINGUAGENS E SUAS TECNOLOGIAS E CIÊNCIAS HUMANAS E SOCIAIS APLICADAS'
  },
  'NEMVESLCHB': {
    'TURNO':
    'VESPERTINO',
    'MODALIDADE':
    'EDUCACAO REGULAR',
    'NÍVEL':
    'ENSINO MÉDIO',
    'OFERTA':
    'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS':
    '2ª SÉRIE - ITINERÁRIO FORMATIVO - LINGUAGENS E SUAS TECNOLOGIAS E CIÊNCIAS HUMANAS E SOCIAIS APLICADAS'
  },
  'NEMVESMCNA': {
    'TURNO':
    'VESPERTINO',
    'MODALIDADE':
    'EDUCACAO REGULAR',
    'NÍVEL':
    'ENSINO MÉDIO',
    'OFERTA':
    'NOVO ENSINO MÉDIO',
    'ANO/SERIE/OUTROS':
    '2ª SÉRIE - ITINERÁRIO FORMATIVO - MATEMÁTICA E SUAS TECNOLOGIAS E CIÊNCIAS DA NATUREZA E SUAS TECNOLOGIAS'
  }
}

prodt = ({
  '113903721': 'ANA PAULA RAMOS BARRETO',
  '113579522': 'ANTONIO PEREIRA DE CARVALHO',
  '112588853': 'CARLESSANDRA COSTA VALENÇA CARVALHO',
  '85200943': 'CAROL FARIAS SILVA',
  '114521661': 'CLEIDE DA LUZ ANDRADE',
  '114506603': 'DANIEL LIMA ALMEIDA MIDLEJ',
  '113858528': 'DEBORA DOS SANTOS SILVA',
  '113601086': 'EDELIANA DI LAURO CUNHA OLIVEIRA',
  '92012460': 'EDSON DE SOUSA RAMALHO GRILO DO OURO',
  '115317544': 'EDUARDO SANTOS SOUZA',
  '92057154': 'ELIANA MARCHI TAVARES',
  '115528187': 'ELISABETE CRISTINA DA SILVA PIRES',
  '115787757': 'ENIO RICARDO LOBO PEREIRA',
  '115312683': 'GRAZIANO SOUZA OLIVEIRA',
  '114543663': 'JEOVANE GOMES DE AZEVEDO',
  '113944036': 'JOAO BATISTA AMORIM CORTES',
  '114120902': 'JOAO KERSON ALVES BRITO',
  '113438988': 'JOSE AMORIM DA SILVA FILHO',
  '113967864': 'JOSE LUIS RIBEIRO BRITO',
  '92083069': 'JOSELINO DOS SANTOS SOUSA',
  '114255294': 'LARISSA BRITTO CARDOSO',
  '114135729': 'LIVIA MARIA MATEUS PRATES',
  '92058338': 'LUCAS RAMOS RUAS',
  '114544059': 'LUCIANO CÉSAR DUARTE OLIVEIRA',
  '115100955': 'MARCELO DA SILVA PIRES',
  '113848905': 'MARIA DA RESSURREICAO DONATO MACEDO GUSMAO',
  '111281131': 'MARIA RITA DE CASSIA TAVARES DIAS',
  '92048735': 'MARLLON DUTRA DE OLIVEIRA',
  '114062154': 'MILENA ALVES DE ANDRADE REQUIAO',
  '113845266': 'NUBIA SALES FIGUEIREDO DE ANDRADE',
  '115528195': 'ODIRLEY ROCHA FERRAZ',
  '114574410': 'PAULO GLEISON CORDEIRO VIANA',
  '115547474': 'PRISCILA ALVES SANTOS FERRAZ DI LAURO',
  '113195247': 'RAQUEL VIEIRA DE MACEDO',
  '114177933': 'RITA DE CASSIA ALBUQUERQUE DE MENEZES',
  '113836940': 'RONALDO OLIVEIRA FERRAZ',
  '114016959': 'RONALDO OLIVEIRA FERRAZ',
  '114153963': 'ROSANGELA NASCIMENTO DE ARAUJO FARIAS',
  '114522528': 'SANTUZA FREIRE AGUIAR MOREIRA GOMES',
  '114191602': 'SATURNINO BARBOSA DOS SANTOS NETO',
  '115547482': 'TAMARA ROCHA SILVA DOURADO',
  '114185871': 'TATIANE SANTOS DA SILVA PAMPONET',
  '114083566': 'USEENE SANTANA LEAL',
  '113958360': 'VALDENOBIA LOPES SOARES',
  '114120889': 'VENOZINA DE OLIVEIRA SOARES',
  '92051136': 'VICTOR ANDRADE SILVA LEAL'
}, {
  '113903721 - ANA PAULA RAMOS BARRETO': '113903721',
  '113579522 - ANTONIO PEREIRA DE CARVALHO': '113579522',
  '112588853 - CARLESSANDRA COSTA VALENÇA CARVALHO': '112588853',
  '85200943 - CAROL FARIAS SILVA': '85200943',
  '114521661 - CLEIDE DA LUZ ANDRADE': '114521661',
  '114506603 - DANIEL LIMA ALMEIDA MIDLEJ': '114506603',
  '113858528 - DEBORA DOS SANTOS SILVA': '113858528',
  '113601086 - EDELIANA DI LAURO CUNHA OLIVEIRA': '113601086',
  '92012460 - EDSON DE SOUSA RAMALHO GRILO DO OURO': '92012460',
  '115317544 - EDUARDO SANTOS SOUZA': '115317544',
  '92057154 - ELIANA MARCHI TAVARES': '92057154',
  '115528187 - ELISABETE CRISTINA DA SILVA PIRES': '115528187',
  '115787757 - ENIO RICARDO LOBO PEREIRA': '115787757',
  '115312683 - GRAZIANO SOUZA OLIVEIRA': '115312683',
  '114543663 - JEOVANE GOMES DE AZEVEDO': '114543663',
  '113944036 - JOAO BATISTA AMORIM CORTES': '113944036',
  '114120902 - JOAO KERSON ALVES BRITO': '114120902',
  '113438988 - JOSE AMORIM DA SILVA FILHO': '113438988',
  '113967864 - JOSE LUIS RIBEIRO BRITO': '113967864',
  '92083069 - JOSELINO DOS SANTOS SOUSA': '92083069',
  '114255294 - LARISSA BRITTO CARDOSO': '114255294',
  '114135729 - LIVIA MARIA MATEUS PRATES': '114135729',
  '92058338 - LUCAS RAMOS RUAS': '92058338',
  '114544059 - LUCIANO CÉSAR DUARTE OLIVEIRA': '114544059',
  '115100955 - MARCELO DA SILVA PIRES': '115100955',
  '113848905 - MARIA DA RESSURREICAO DONATO MACEDO GUSMAO': '113848905',
  '111281131 - MARIA RITA DE CASSIA TAVARES DIAS': '111281131',
  '92048735 - MARLLON DUTRA DE OLIVEIRA': '92048735',
  '114062154 - MILENA ALVES DE ANDRADE REQUIAO': '114062154',
  '113845266 - NUBIA SALES FIGUEIREDO DE ANDRADE': '113845266',
  '115528195 - ODIRLEY ROCHA FERRAZ': '115528195',
  '114574410 - PAULO GLEISON CORDEIRO VIANA': '114574410',
  '115547474 - PRISCILA ALVES SANTOS FERRAZ DI LAURO': '115547474',
  '113195247 - RAQUEL VIEIRA DE MACEDO': '113195247',
  '114177933 - RITA DE CASSIA ALBUQUERQUE DE MENEZES': '114177933',
  '113836940 - RONALDO OLIVEIRA FERRAZ': '113836940',
  '114016959 - RONALDO OLIVEIRA FERRAZ': '114016959',
  '114153963 - ROSANGELA NASCIMENTO DE ARAUJO FARIAS': '114153963',
  '114522528 - SANTUZA FREIRE AGUIAR MOREIRA GOMES': '114522528',
  '114191602 - SATURNINO BARBOSA DOS SANTOS NETO': '114191602',
  '115547482 - TAMARA ROCHA SILVA DOURADO': '115547482',
  '114185871 - TATIANE SANTOS DA SILVA PAMPONET': '114185871',
  '114083566 - USEENE SANTANA LEAL': '114083566',
  '113958360 - VALDENOBIA LOPES SOARES': '113958360',
  '114120889 - VENOZINA DE OLIVEIRA SOARES': '114120889',
  '92051136 - VICTOR ANDRADE SILVA LEAL': '92051136'
})

programação = {
  '85200943': {
    'NEMVESLCHA': ['EDUCACAO FISICA'],
    'NEMVESLCHB': ['EDUCACAO FISICA'],
    'NEMVESMCNA': ['EDUCACAO FISICA'],
    'EMVES3A': ['EDUCACAO FISICA'],
    'EMVES3B': ['EDUCACAO FISICA'],
    'NEMMATLCHA': ['EDUCACAO FISICA'],
    'NEMMATLCHB': ['EDUCACAO FISICA'],
    'NEMMATMCNA': ['EDUCACAO FISICA'],
    'NEMMATTIA': ['EDUCACAO FISICA'],
    'EMMAT3A': ['EDUCACAO FISICA'],
    'PIINT7T1A': ['EDUCACAO FISICA'],
    'PIINT7T1B': ['EDUCACAO FISICA'],
    'PIINT7T1C': ['EDUCACAO FISICA'],
    'PIINT7T1D': ['EDUCACAO FISICA'],
    'PIINT7T1E': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES',
      'EDUCACAO FISICA'
    ],
    'PIINT7T1F': ['EDUCACAO FISICA'],
    'PIINT7T1G': ['EDUCACAO FISICA']
  },
  '92012460': {
    'NEMMATTIA': ['ELETIVA'],
    'PIINT7T1A': ['FILOSOFIA'],
    'PIINT7T1E': ['FILOSOFIA'],
    'PIINT7T1F': ['FILOSOFIA'],
    'EJAJ3NOTJ3E6A': ['ELETIVA I'],
    'EJAJ3NOTJ3E6B': ['ELETIVA II'],
    'EJAJ3NOTJ3E6C': ['ELETIVA I', 'ELETIVA II'],
    'TFS3NOTF2E6A': ['ELETIVA I'],
    'TFS3NOTF2E6B': ['ELETIVA I', 'FILOSOFIA'],
    'TFS3NOTF2E6C': ['ELETIVA I', 'FILOSOFIA'],
    'TFS3NOTTFE7B': ['ELETIVA I']
  },
  '92048735': {
    'NEMMATLCHA': ['QUIMICA'],
    'NEMMATLCHB': ['QUIMICA'],
    'EMMAT3A': ['BIOLOGIA'],
    'PIINT7T1A': ['ESTACAO DO SABER IX - TECNICO PROFISSIONAL'],
    'PIINT7T1B': ['ESTACAO DO SABER IX - TECNICO PROFISSIONAL'],
    'PIINT7T1C': ['ESTACAO DO SABER IX - TECNICO PROFISSIONAL'],
    'PIINT7T1D': ['ESTACAO DO SABER IX - TECNICO PROFISSIONAL'],
    'PIINT7T1E': ['ESTACAO DO SABER IX - TECNICO PROFISSIONAL'],
    'PIINT7T1F': ['ESTACAO DO SABER IX - TECNICO PROFISSIONAL'],
    'EJAJ3NOTJ3E6C': ['QUIMICA'],
    'TFS3NOTF2E6C': ['QUIMICA'],
    'EJAJ3NOTJ3E7A': ['FISICA'],
    'TFS3NOTTFE7A': ['BIOLOGIA', 'FISICA'],
    'TFS3NOTTFE7B': ['FISICA']
  },
  '92051136': {
    'NEMVESLCHA': ['GEOGRAFIA'],
    'NEMVESLCHB': ['GEOGRAFIA'],
    'NEMVESMCNA': ['COSMOS: DO MICRO AO MACRO', 'GEOGRAFIA'],
    'NEMMATLCHA': ['PROJETO DE VIDA', 'GEOGRAFIA'],
    'NEMMATLCHB': ['PROJETO DE VIDA'],
    'NEMMATMCNA': ['PROJETO DE VIDA', 'COSMOS: DO MICRO AO MACRO'],
    'NEMMATTIA': ['PROJETO DE VIDA'],
    'PIINT7T1B': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1D': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1E': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1F': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1G': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ]
  },
  '92057154': {
    'TFS3NOTF2E6A': ['ARTE'],
    'TFS3NOTF2E6B': ['ARTE'],
    'TFS3NOTF2E6C': ['ARTE'],
    'NEMMATMCNA': ['LINGUA PORTUGUESA', 'ARTE'],
    'NEMMATTIA': ['LINGUA PORTUGUESA'],
    'PIINT7T1B': ['LINGUA PORTUGUESA'],
    'PIINT7T1C': ['LINGUA PORTUGUESA'],
    'PIINT7T1D': ['LINGUA PORTUGUESA', 'ARTE'],
    'PIINT7T1H': ['LINGUA PORTUGUESA', 'ARTE']
  },
  '92058338': {
    'NEMMATMCNA': ['HISTORIA'],
    'NEMMATTIA': ['HISTORIA'],
    'PIINT7T1A': ['HISTORIA'],
    'PIINT7T1B': ['HISTORIA'],
    'PIINT7T1C': ['HISTORIA'],
    'PIINT7T1D': ['HISTORIA'],
    'PIINT7T1E': ['HISTORIA'],
    'PIINT7T1F': ['HISTORIA'],
    'PIINT7T1G': ['HISTORIA'],
    'PIINT7T1H': ['HISTORIA']
  },
  '92083069': {
    'PIINT7T1B': [
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'PIINT7T1A': [
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'EJAJ3NOTJ3E6A': ['INCLUSAO DIGITAL'],
    'EJAJ3NOTJ3E6B': ['INCLUSAO DIGITAL'],
    'EJAJ3NOTJ3E6C': ['INCLUSAO DIGITAL'],
    'TFS3NOTF2E6A': ['INCLUSAO DIGITAL'],
    'TFS3NOTF2E6B': ['INCLUSAO DIGITAL', 'GEOGRAFIA'],
    'TFS3NOTF2E6C': ['INCLUSAO DIGITAL', 'GEOGRAFIA'],
    'EJAJ3NOTJ3E7A': ['INCLUSAO DIGITAL'],
    'TFS3NOTTFE7A': ['INCLUSAO DIGITAL', 'ARTE'],
    'TFS3NOTTFE7B': ['INCLUSAO DIGITAL']
  },
  '111281131': {
    'PIINT7T1A': [
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'EJAJ3NOTJ3E6A': ['INCLUSAO DIGITAL'],
    'EJAJ3NOTJ3E6B': ['INCLUSAO DIGITAL'],
    'EJAJ3NOTJ3E6C': ['INCLUSAO DIGITAL'],
    'TFS3NOTF2E6A': ['INCLUSAO DIGITAL'],
    'TFS3NOTF2E6B': ['INCLUSAO DIGITAL', 'GEOGRAFIA'],
    'TFS3NOTF2E6C': ['INCLUSAO DIGITAL', 'GEOGRAFIA'],
    'EJAJ3NOTJ3E7A': ['INCLUSAO DIGITAL'],
    'TFS3NOTTFE7A': ['INCLUSAO DIGITAL', 'ARTE'],
    'TFS3NOTTFE7B': ['INCLUSAO DIGITAL']
  },
  '112588853': {
    'NEMMATLCHA': ['MEU CORPO NO MUNDO'],
    'NEMMATLCHB': ['MEU CORPO NO MUNDO', 'ARTE'],
    'NEMMATMCNA': ['A ARTE DE MORAR'],
    'PIINT7T1A': ['LINGUA PORTUGUESA', 'ARTE'],
    'PIINT7T1B': ['ARTE'],
    'PIINT7T1C': ['ARTE'],
    'PIINT7T1D': [
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1E': [
      'ARTE',
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'PIINT7T1F': [
      'ARTE',
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'PIINT7T1G': [
      'ARTE',
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ]
  },
  '113195247': {
    'NEMMATLCHA': ['LINGUA PORTUGUESA'],
    'NEMMATLCHB': ['LINGUA PORTUGUESA'],
    'EMMAT3A': ['LINGUA PORTUGUESA'],
    'EMMAT3B': ['LINGUA PORTUGUESA'],
    'EMMAT3C': ['LINGUA PORTUGUESA']
  },
  '113438988': {
    'EJAJ3NOTJ3E7A': ['GEOGRAFIA'],
    'TFS3NOTTFE7A': ['ELETIVA I', 'GEOGRAFIA'],
    'TFS3NOTTFE7B': ['GEOGRAFIA'],
    'EMNOT3A': ['GEOGRAFIA'],
    'EMNOT3B': ['GEOGRAFIA'],
    'EMNOT3C': ['GEOGRAFIA']
  },
  '113579522': {
    'EJAJ3NOTJ3E6A': ['GEOGRAFIA'],
    'EJAJ3NOTJ3E6B': ['GEOGRAFIA'],
    'EJAJ3NOTJ3E6C': ['GEOGRAFIA'],
    'TFS3NOTF2E6A': ['GEOGRAFIA'],
    'EMNOT3A': ['FILOSOFIA'],
    'EMNOT3B': ['FILOSOFIA'],
    'EMNOT3C': ['FILOSOFIA']
  },
  '113601086': {
    'NEMVESLCHA': ['LINGUA PORTUGUESA'],
    'NEMVESLCHB': ['LINGUA PORTUGUESA'],
    'NEMVESMCNA': ['LINGUA PORTUGUESA', 'ARTE'],
    'EMVES3A': ['LINGUA PORTUGUESA'],
    'EMVES3B': ['LINGUA PORTUGUESA']
  },
  '113836940': {
    'NEMVESLCHA': ['SOCIOLOGIA'],
    'NEMVESLCHB': ['SOCIOLOGIA'],
    'EMVES3A': ['SOCIOLOGIA'],
    'EMVES3B': ['SOCIOLOGIA'],
    'PIINT7T1A': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'PIINT7T1B': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'NEMMATLCHA': ['SOCIOLOGIA'],
    'NEMMATLCHB': ['SOCIOLOGIA'],
    'NEMMATMCNA': ['SOCIOLOGIA'],
    'NEMMATTIA': ['SOCIOLOGIA'],
    'EMMAT3A': ['SOCIOLOGIA'],
    'EMMAT3B': ['SOCIOLOGIA'],
    'EMMAT3C': ['SOCIOLOGIA'],
    'PIINT7T1D': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'PIINT7T1E': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ]
  },
  '113845266': {
    'NEMVESLCHA': ['LINGUA INGLESA'],
    'NEMVESLCHB': ['LINGUA INGLESA'],
    'NEMVESMCNA': ['LINGUA INGLESA'],
    'EMVES3A': ['LINGUA ESTRANGEIRA MODERNA'],
    'EMVES3B': ['LINGUA ESTRANGEIRA MODERNA'],
    'PIINT7T1D': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'PIINT7T1F': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'EJAJ3NOTJ3E6A': ['LINGUA INGLESA'],
    'EJAJ3NOTJ3E6B': ['LINGUA INGLESA'],
    'EJAJ3NOTJ3E6C': ['LINGUA INGLESA'],
    'TFS3NOTF2E6A': ['LINGUA INGLESA'],
    'TFS3NOTF2E6B': ['LINGUA INGLESA'],
    'TFS3NOTF2E6C': ['LINGUA INGLESA'],
    'EJAJ3NOTJ3E7A': ['LINGUA INGLESA'],
    'TFS3NOTTFE7A': ['LINGUA INGLESA'],
    'TFS3NOTTFE7B': ['LINGUA INGLESA'],
    'EMNOT3A': ['LINGUA ESTRANGEIRA MODERNA'],
    'EMNOT3B': ['LINGUA ESTRANGEIRA MODERNA'],
    'EMNOT3C': ['LINGUA ESTRANGEIRA MODERNA']
  },
  '113848905': {
    'EMVES3A': ['FISICA'],
    'EMVES3B': ['FISICA'],
    'NEMMATMCNA': ['FISICA'],
    'PIINT7T1A': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'PIINT7T1B': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'PIINT7T1H': ['FISICA']
  },
  '113858528': {
    'NEMMATLCHA': ['MATEMATICA'],
    'NEMMATLCHB': ['MATEMATICA'],
    'NEMMATMCNA': ['ELETIVA'],
    'NEMMATTIA': [
      'SAÚDE INTEGRAL, AGRICULTURA E SOBERANIA ALIMENTAR',
      'TOMANDO DECISÕES A PARTIR DOS NÚMEROS'
    ],
    'PIINT7T1A': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1B': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1D': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1E': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1F': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1G': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER V - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ECOSSISTEMA E A DINAMICA DA RELACAO'
    ]
  },
  '113903721': {
    'NEMMATLCHA': ['LINGUA INGLESA'],
    'NEMMATLCHB': ['LINGUA INGLESA'],
    'NEMMATMCNA': ['LINGUA INGLESA'],
    'NEMMATTIA': ['LINGUA INGLESA'],
    'EMMAT3A': ['LINGUA ESTRANGEIRA MODERNA'],
    'EMMAT3B': ['LINGUA ESTRANGEIRA MODERNA'],
    'EMMAT3C': ['LINGUA ESTRANGEIRA MODERNA'],
    'PIINT7T1A': [
      'INGLES',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1B': [
      'INGLES',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1C': [
      'INGLES',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1D': ['INGLES'],
    'PIINT7T1E': [
      'INGLES',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1F': ['INGLES'],
    'PIINT7T1G': ['INGLES'],
    'PIINT7T1H': ['INGLES']
  },
  '113944036': {
    'TFS3NOTF2E6A': ['BIOLOGIA'],
    'TFS3NOTF2E6B': ['BIOLOGIA'],
    'TFS3NOTF2E6C': ['BIOLOGIA'],
    'TFS3NOTTFE7B': ['BIOLOGIA'],
    'EMNOT3A': ['BIOLOGIA'],
    'EMNOT3B': ['BIOLOGIA'],
    'EMNOT3C': ['BIOLOGIA']
  },
  '113958360': {
    'NEMVESLCHA': ['ARTE', 'LITERATURA DE MEUS ANCESTRAIS'],
    'NEMVESLCHB': ['LITERATURA DE MEUS ANCESTRAIS'],
    'EMVES3A': ['DIVERSIFICADA I'],
    'EMVES3B': ['DIVERSIFICADA I'],
    'EJAJ3NOTJ3E6A': ['LINGUA PORTUGUESA'],
    'EJAJ3NOTJ3E6B': ['LINGUA PORTUGUESA'],
    'TFS3NOTF2E6A': ['LINGUA PORTUGUESA'],
    'TFS3NOTF2E6B': ['LINGUA PORTUGUESA'],
    'TFS3NOTF2E6C': ['LINGUA PORTUGUESA']
  },
  '113967864': {
    'EJAJ3NOTJ3E7A': ['MATEMATICA', 'ELETIVA II'],
    'EMNOT3A': ['MATEMATICA'],
    'EMNOT3B': ['MATEMATICA'],
    'EMNOT3C': ['MATEMATICA']
  },
  '114016959': {
    'NEMMATLCHA': ['SOCIOLOGIA'],
    'NEMMATLCHB': ['SOCIOLOGIA'],
    'NEMMATMCNA': ['SOCIOLOGIA'],
    'NEMMATTIA': ['SOCIOLOGIA'],
    'EMMAT3A': ['SOCIOLOGIA'],
    'EMMAT3B': ['SOCIOLOGIA'],
    'EMMAT3C': ['SOCIOLOGIA'],
    'PIINT7T1D': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'PIINT7T1E': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ]
  },
  '114062154': {
    'PIINT7T1E': ['LINGUA PORTUGUESA'],
    'PIINT7T1F': ['LINGUA PORTUGUESA'],
    'PIINT7T1G': ['LINGUA PORTUGUESA'],
    'EJAJ3NOTJ3E7A': ['LINGUA PORTUGUESA'],
    'TFS3NOTTFE7A': ['LINGUA PORTUGUESA'],
    'TFS3NOTTFE7B': ['LINGUA PORTUGUESA', 'ARTE'],
    'EMNOT3A': ['LINGUA PORTUGUESA'],
    'EMNOT3B': ['LINGUA PORTUGUESA'],
    'EMNOT3C': ['LINGUA PORTUGUESA']
  },
  '114083566': {
    'NEMVESLCHA': ['FILOSOFIA'],
    'NEMVESLCHB': ['FILOSOFIA'],
    'EMVES3A': ['FILOSOFIA'],
    'EMVES3B': ['FILOSOFIA'],
    'PIINT7T1F': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'PIINT7T1G': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER VII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: IDENTIDADE, PERTENCIMENTO COM ENFASE EM RELACOES ETNICO RACIAIS'
    ]
  },
  '114120889': {
    'PIINT7T1A': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE',
      'GEOGRAFIA'
    ],
    'PIINT7T1B': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE',
      'GEOGRAFIA'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE',
      'GEOGRAFIA'
    ],
    'PIINT7T1D': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE',
      'GEOGRAFIA'
    ],
    'PIINT7T1E': ['GEOGRAFIA']
  },
  '114120902': {
    'NEMVESLCHA': ['HISTÓRIAS QUE EU ESQUECI DE LEMBRAR', 'HISTORIA'],
    'NEMVESLCHB': ['HISTÓRIAS QUE EU ESQUECI DE LEMBRAR', 'HISTORIA'],
    'NEMVESMCNA': ['HISTORIA'],
    'EMVES3A': ['HISTORIA'],
    'EMVES3B': ['HISTORIA'],
    'EJAJ3NOTJ3E6A': ['FILOSOFIA'],
    'EJAJ3NOTJ3E6B': ['FILOSOFIA'],
    'EJAJ3NOTJ3E6C': ['FILOSOFIA'],
    'TFS3NOTF2E6A': ['FILOSOFIA'],
    'TFS3NOTF2E6B': ['HISTORIA'],
    'TFS3NOTF2E6C': ['HISTORIA'],
    'EJAJ3NOTJ3E7A': ['HISTORIA', 'FILOSOFIA'],
    'TFS3NOTTFE7A': ['HISTORIA', 'FILOSOFIA'],
    'TFS3NOTTFE7B': ['HISTORIA', 'FILOSOFIA']
  },
  '114135729': {
    'NEMVESLCHA': ['ELETIVA', 'MATEMATICA'],
    'NEMVESLCHB': ['ELETIVA', 'MATEMATICA'],
    'NEMVESMCNA': ['ELETIVA', 'MATEMATICA'],
    'EJAJ3NOTJ3E6A': ['MATEMATICA', 'ELETIVA II'],
    'EJAJ3NOTJ3E6B': ['MATEMATICA'],
    'EJAJ3NOTJ3E6C': ['MATEMATICA'],
    'TFS3NOTF2E6A': ['MATEMATICA'],
    'TFS3NOTF2E6B': ['MATEMATICA'],
    'TFS3NOTF2E6C': ['MATEMATICA']
  },
  '114153963': {
    'NEMVESMCNA': ['A CIDADE EM MOVIMENTO'],
    'EMVES3A': ['GEOGRAFIA'],
    'EMVES3B': ['GEOGRAFIA'],
    'NEMMATLCHB': ['GEOGRAFIA'],
    'NEMMATMCNA': ['A CIDADE EM MOVIMENTO', 'GEOGRAFIA'],
    'NEMMATTIA': ['GEOGRAFIA'],
    'EMMAT3A': ['GEOGRAFIA'],
    'EMMAT3B': ['GEOGRAFIA'],
    'EMMAT3C': ['GEOGRAFIA'],
    'PIINT7T1F': [
      'GEOGRAFIA',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1G': [
      'GEOGRAFIA',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ],
    'PIINT7T1H': [
      'GEOGRAFIA',
      'ESTACAO DO SABER III - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: EMPREENDEDORISMO E INOVACAO COM ENFASE NA TERRITORIALIDADE'
    ]
  },
  '114177933': {
    'EJAJ3NOTJ3E6A': ['HISTORIA'],
    'EJAJ3NOTJ3E6B': ['HISTORIA'],
    'EJAJ3NOTJ3E6C': ['HISTORIA'],
    'TFS3NOTF2E6A': ['HISTORIA'],
    'EMNOT3A': ['HISTORIA'],
    'EMNOT3B': ['HISTORIA'],
    'EMNOT3C': ['HISTORIA']
  },
  '114185871': {
    'EMVES3A': ['MATEMATICA'],
    'EMVES3B': ['MATEMATICA'],
    'NEMMATTIA': ['MATEMATICA'],
    'EMMAT3A': ['MATEMATICA'],
    'EMMAT3B': ['MATEMATICA'],
    'PIINT7T1A': ['MATEMATICA'],
    'PIINT7T1B': ['MATEMATICA'],
    'PIINT7T1C': ['MATEMATICA'],
    'PIINT7T1D': ['MATEMATICA'],
    'PIINT7T1E': ['MATEMATICA'],
    'PIINT7T1F': ['MATEMATICA']
  },
  '114191602': {
    'EMMAT3B': ['EDUCACAO FISICA'],
    'EMMAT3C': ['EDUCACAO FISICA'],
    'PIINT7T1H': ['EDUCACAO FISICA'],
    'EJAJ3NOTJ3E6A': ['EDUCACAO FISICA'],
    'EJAJ3NOTJ3E6B': ['EDUCACAO FISICA'],
    'EJAJ3NOTJ3E6C': ['EDUCACAO FISICA'],
    'TFS3NOTF2E6A': ['EDUCACAO FISICA'],
    'TFS3NOTF2E6B': ['EDUCACAO FISICA'],
    'TFS3NOTF2E6C': ['EDUCACAO FISICA'],
    'EJAJ3NOTJ3E7A': ['EDUCACAO FISICA'],
    'TFS3NOTTFE7A': ['EDUCACAO FISICA'],
    'TFS3NOTTFE7B': ['EDUCACAO FISICA']
  },
  '114255294': {
    'NEMVESLCHA': ['MEU CORPO NO MUNDO'],
    'NEMVESLCHB': ['MEU CORPO NO MUNDO', 'ARTE'],
    'PIINT7T1D': ['ESTACAO DO SABER X - TECNICO PROFISSIONAL'],
    'PIINT7T1G': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER II - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: CORPOREIDADES'
    ],
    'EJAJ3NOTJ3E6A': ['ARTE'],
    'EJAJ3NOTJ3E6B': ['ARTE'],
    'EJAJ3NOTJ3E6C': ['LINGUA PORTUGUESA', 'ARTE'],
    'EJAJ3NOTJ3E7A': ['ELETIVA I', 'ARTE'],
    'EMNOT3A': ['DIVERSIFICADA I'],
    'EMNOT3B': ['DIVERSIFICADA I'],
    'EMNOT3C': ['DIVERSIFICADA I']
  },
  '114506603': {
    'PIINT7T1D': [
      'ESTACAO DO SABER IV - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: PENSAMENTO COMPUTACIONAL'
    ],
    'PIINT7T1G': ['MATEMATICA'],
    'PIINT7T1H': ['MATEMATICA'],
    'EJAJ3NOTJ3E6A': ['FISICA'],
    'EJAJ3NOTJ3E6B': ['ELETIVA I', 'FISICA'],
    'EJAJ3NOTJ3E6C': ['FISICA'],
    'TFS3NOTF2E6A': ['FISICA', 'ELETIVA II'],
    'TFS3NOTF2E6B': ['FISICA', 'ELETIVA II'],
    'TFS3NOTF2E6C': ['FISICA', 'ELETIVA II'],
    'TFS3NOTTFE7A': ['MATEMATICA', 'ELETIVA II'],
    'TFS3NOTTFE7B': ['MATEMATICA', 'ELETIVA II']
  },
  '114521661': {
    'NEMMATMCNA': ['LINGUA PORTUGUESA', 'ARTE'],
    'NEMMATTIA': ['LINGUA PORTUGUESA'],
    'PIINT7T1B': ['LINGUA PORTUGUESA'],
    'PIINT7T1C': ['LINGUA PORTUGUESA'],
    'PIINT7T1D': ['LINGUA PORTUGUESA', 'ARTE'],
    'PIINT7T1H': ['LINGUA PORTUGUESA', 'ARTE']
  },
  '114522528': {
    'NEMMATLCHA': ['LITERATURA DE MEUS ANCESTRAIS'],
    'NEMMATLCHB': ['LITERATURA DE MEUS ANCESTRAIS'],
    'NEMMATTIA': ['ARTE'],
    'EMMAT3A': ['DIVERSIFICADA I'],
    'EMMAT3B': ['DIVERSIFICADA I'],
    'EMMAT3C': ['DIVERSIFICADA I']
  },
  '114543663': {
    'NEMMATLCHA': ['HISTÓRIAS QUE EU ESQUECI DE LEMBRAR', 'HISTORIA'],
    'NEMMATLCHB': ['HISTÓRIAS QUE EU ESQUECI DE LEMBRAR', 'HISTORIA'],
    'NEMMATTIA': ['A HISTÓRIA DE MEUS ANCESTRAIS'],
    'EMMAT3A': ['HISTORIA'],
    'EMMAT3B': ['HISTORIA'],
    'EMMAT3C': ['HISTORIA']
  },
  '114544059': {
    'EJAJ3NOTJ3E6A': ['SOCIOLOGIA'],
    'EJAJ3NOTJ3E6B': ['SOCIOLOGIA'],
    'EJAJ3NOTJ3E6C': ['SOCIOLOGIA'],
    'TFS3NOTF2E6A': ['SOCIOLOGIA'],
    'TFS3NOTF2E6B': ['SOCIOLOGIA'],
    'TFS3NOTF2E6C': ['SOCIOLOGIA'],
    'EJAJ3NOTJ3E7A': ['SOCIOLOGIA'],
    'TFS3NOTTFE7A': ['SOCIOLOGIA'],
    'TFS3NOTTFE7B': ['SOCIOLOGIA'],
    'EMNOT3A': ['SOCIOLOGIA'],
    'EMNOT3B': ['SOCIOLOGIA'],
    'EMNOT3C': ['SOCIOLOGIA']
  },
  '114574410': {
    'NEMMATLCHA': ['BIOLOGIA'],
    'NEMMATLCHB': ['BIOLOGIA'],
    'NEMMATMCNA': ['BIOLOGIA'],
    'NEMMATTIA': ['BIOLOGIA'],
    'EMMAT3B': ['BIOLOGIA'],
    'EMMAT3C': ['BIOLOGIA'],
    'EJAJ3NOTJ3E6A': ['BIOLOGIA', 'QUIMICA'],
    'EJAJ3NOTJ3E6B': ['BIOLOGIA', 'QUIMICA'],
    'EJAJ3NOTJ3E6C': ['BIOLOGIA'],
    'TFS3NOTF2E6A': ['QUIMICA'],
    'TFS3NOTF2E6B': ['QUIMICA'],
    'EJAJ3NOTJ3E7A': ['BIOLOGIA']
  },
  '115100955': {
    'EJAJ3NOTJ3E7A': ['QUIMICA'],
    'TFS3NOTTFE7A': ['QUIMICA'],
    'TFS3NOTTFE7B': ['QUIMICA'],
    'EMNOT3A': ['QUIMICA'],
    'EMNOT3B': ['QUIMICA'],
    'EMNOT3C': ['QUIMICA']
  },
  '115317544': {
    'NEMVESLCHA': ['QUIMICA'],
    'NEMVESLCHB': ['QUIMICA'],
    'NEMVESMCNA': ['QUIMICA'],
    'EMVES3A': ['QUIMICA'],
    'EMVES3B': ['QUIMICA'],
    'NEMMATLCHA': ['FISICA'],
    'NEMMATLCHB': ['FISICA'],
    'NEMMATMCNA': ['QUIMICA'],
    'NEMMATTIA': ['FISICA', 'QUIMICA'],
    'EMMAT3A': ['QUIMICA'],
    'EMMAT3B': ['QUIMICA'],
    'EMMAT3C': ['QUIMICA'],
    'PIINT7T1A': ['QUIMICA'],
    'PIINT7T1B': ['QUIMICA'],
    'PIINT7T1C': ['QUIMICA'],
    'PIINT7T1D': ['QUIMICA'],
    'PIINT7T1E': ['QUIMICA'],
    'PIINT7T1F': ['QUIMICA'],
    'PIINT7T1G': ['QUIMICA'],
    'PIINT7T1H': ['QUIMICA']
  },
  '115528187': {
    'NEMVESLCHA': ['FISICA'],
    'NEMVESLCHB': ['FISICA'],
    'NEMVESMCNA': ['A ARTE DE MORAR', 'FISICA'],
    'NEMMATMCNA': ['MATEMATICA'],
    'EMMAT3C': ['MATEMATICA'],
    'PIINT7T1A': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1B': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1C': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1D': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1E': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1F': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1G': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER I - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: INICIACAO CIENTIFICA E INTERMEDIACAO SOCIAL'
    ]
  },
  '115528195': {
    'NEMVESLCHA': ['PROJETO DE VIDA'],
    'NEMVESLCHB': ['PROJETO DE VIDA'],
    'NEMVESMCNA': ['PROJETO DE VIDA', 'SOCIOLOGIA', 'FILOSOFIA'],
    'NEMMATLCHA': ['FILOSOFIA'],
    'NEMMATLCHB': ['FILOSOFIA'],
    'NEMMATMCNA': ['FILOSOFIA'],
    'NEMMATTIA': ['FILOSOFIA'],
    'EMMAT3A': ['FILOSOFIA'],
    'EMMAT3B': ['FILOSOFIA'],
    'EMMAT3C': ['FILOSOFIA'],
    'PIINT7T1A': [
      'ESTACAO DO SABER VIII - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: SABERES DA DIASPORA E DIREITOS SOCIAIS E HUMANOS'
    ],
    'PIINT7T1B': ['FILOSOFIA'],
    'PIINT7T1C': ['FILOSOFIA'],
    'PIINT7T1D': ['FILOSOFIA'],
    'PIINT7T1E': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE'
    ],
    'PIINT7T1F': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE'
    ],
    'PIINT7T1G': ['FILOSOFIA'],
    'PIINT7T1H': ['FILOSOFIA']
  },
  '115547474': {
    'NEMMATLCHA': ['ELETIVA', 'ARTE'],
    'NEMMATLCHB': ['ELETIVA'],
    'NEMMATTIA': ['LINGUAGEM, LITERATURA E EMPODERAMENTO SOCIAL'],
    'PIINT7T1F': ['ESTACAO DO SABER X - TECNICO PROFISSIONAL'],
    'PIINT7T1G': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER VI - VIVENCIAS E PRATICAS EXPERIMENTAIS TRANSDISCIPLINARES: ETICA E MEIO AMBIENTE'
    ]
  },
  '115547482': {
    'NEMVESLCHA': ['BIOLOGIA'],
    'NEMVESLCHB': ['BIOLOGIA'],
    'NEMVESMCNA': ['BIOLOGIA'],
    'EMVES3A': ['BIOLOGIA'],
    'EMVES3B': ['BIOLOGIA'],
    'PIINT7T1A': ['ESTACAO DO SABER X - TECNICO PROFISSIONAL'],
    'PIINT7T1B': ['ESTACAO DO SABER X - TECNICO PROFISSIONAL'],
    'PIINT7T1C': ['ESTACAO DO SABER X - TECNICO PROFISSIONAL'],
    'PIINT7T1E': ['ESTACAO DO SABER X - TECNICO PROFISSIONAL'],
    'PIINT7T1G': [
      'ESTACAO DO SABER IX - TECNICO PROFISSIONAL',
      'ESTACAO DO SABER X - TECNICO PROFISSIONAL'
    ],
    'PIINT7T1H': [
      'ESTACAO DO SABER IX - TECNICO PROFISSIONAL',
      'ESTACAO DO SABER X - TECNICO PROFISSIONAL'
    ]
  },
  '115787757': {
    'EMMAT3A': ['FISICA'],
    'EMMAT3B': ['FISICA'],
    'EMMAT3C': ['FISICA'],
    'PIINT7T1A': ['FISICA'],
    'PIINT7T1B': ['FISICA'],
    'PIINT7T1C': ['FISICA'],
    'PIINT7T1D': ['FISICA'],
    'PIINT7T1E': ['FISICA'],
    'PIINT7T1F': ['FISICA'],
    'PIINT7T1G': ['FISICA'],
    'EMNOT3A': ['FISICA'],
    'EMNOT3B': ['FISICA'],
    'EMNOT3C': ['FISICA']
  }
}
